# cmd/web/.air.toml
root = "."
tmp_dir = "tmp"
cmd = "go run main.go"

[build]
bin = "tmp/main"
full_bin = "tmp/main"
delay = 1000 # время задержки в миллисекундах

[log]
level = "info"
file = "build.log"

[error_log]
file = "build-errors.log"


#root = ".": Устанавливает корневой каталог для инструмента Air. В данном случае, он указывает на текущий каталог (".").
#
#tmp_dir = "tmp": Определяет временный каталог для хранения исполняемых файлов и других данных, создаваемых Air. Здесь используется подкаталог "tmp" в корневом каталоге.
#
#cmd = "go run main.go": Определяет команду, которую Air будет выполнять при запуске вашего приложения. В данном случае, он будет запускать ваш сервер с помощью команды go run main.go.
#
#[build]: Начало секции настроек сборки.
#
#bin = "tmp/main": Определяет имя исполняемого файла, который будет создан при сборке. В данном случае, файл будет называться "main" и будет находиться в подкаталоге "tmp".
#
#full_bin = "tmp/main": Определяет полный путь к исполняемому файлу, который будет создан при сборке. Здесь указано то же значение, что и для bin.
#
#delay = 1000: Устанавливает время задержки в миллисекундах перед перезапуском сервера после обнаружения изменений в файлах. В данном случае, задержка составляет 1 секунду (1000 миллисекунд).
#
#[log]: Начало секции настроек логирования.
#
#level = "info": Устанавливает уровень логирования. Здесь используется уровень "info", который включает информационные сообщения, предупреждения и ошибки.
#
#file = "build.log": Определяет файл для записи журнала событий сборки. В данном случае, журнал будет записываться в файл "build.log" в корневом каталоге.
#
#[error_log]: Начало секции настроек логирования ошибок.
#
#file = "build-errors.log": Определяет файл для записи журнала ошибок. В данном случае, журнал ошибок будет записываться в файл "build-errors.log" в корневом каталоге.
